services:
  web:
    restart: always
    build: .
    args:
      - GIT_COMMIT=${GIT_COMMIT}
    ports:
      - "127.0.0.1:8000:8080"
    volumes:
      - type: bind
        source: ${DOC_PATH}
        target: /doc
        read_only: true
