services:
  web:
    restart: always
    build: 
      context: .
      args:
        - GIT_COMMIT=${GIT_COMMIT}
    ports:
      - "127.0.0.1:${LOCAL_PORT}:8080"
    volumes:
      - type: bind
        source: ${DOC_PATH}
        target: /doc
        read_only: true
