name: Zip Files

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Generate logos zip file'
        default: 'yes'
        required: true
        type: string
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: rocq-id/ 
          dest: rocq-logos.zip
      - uses: actions/upload-artifact@v4.4.3
        with:
          name: rocq-logos
          path: ${{ github.workspace }}/rocq-id/
